### ISSUE TITLE
Are there any trained forward/backward models checkpoints available?

### ISSUE THREAD

**Issue by queliyong** [rxn4chemistry/rxn-neb#1]
Hi,
Thanks for this nice project! But are there any trained forward/backward models checkpoints available to reproduce the results? Thanks!

**Comment by drugilsberg** [comment]
Hi @queliyong thanks a lot for the interest in our work. We do not have shareable checkpoints, but it is relatively easy to train your own using the instructions and the code base we provide in https://github.com/rxn4chemistry/rxn-onmt-models.
There you find all the details on how to format your dataset and set the parameters for training both backward and forward models.
